default: &default
  adapter: postgresql
  encoding: unicode
  password: postgres
  host: localhost
  username: postgres
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: icecream_api_development

test:
  <<: *default
  database: icecream_api_test

production:
  <<: *default
  database: icecream_api_production
  username: icecream_api
  password: <%= ENV["ICECREAM_API_DATABASE_PASSWORD"] %>
